### PR TITLE
feature/429 - Remove alert for back end errors

### PR DESCRIPTION
**Pull request by sasha-dresden**
Issue [FECFILE-429](https://fecgov.atlassian.net/browse/FECFILE-429)

### CODE REVIEW

**Comment by dheitzer** [comment]
Do you know if the intention is to fail silently on server errors? It just seems like some indication to the user that something went wrong be good.  Maybe this is a ux discussion.

**Review by dheitzer — APPROVED** [review]

**Comment by sasha-dresden** [comment]
> Do you know if the intention is to fail silently on server errors? It just seems like some indication to the user that something went wrong be good. Maybe this is a ux discussion.

Yea, I believe there was a little discussion about this previously in slack, but for this ticket it's just removing the alert. There should  eventually be a UX ticket to add an error page or some way to allow the user to know something went wrong. For example, to test this I tried going to a a transaction that didn't exist for the report. I should probably get a 404 page, but currently it just redirects you back to the landing page with any indication something went wrong in the console.

**Comment by dheitzer** [comment]
> > Do you know if the intention is to fail silently on server errors? It just seems like some indication to the user that something went wrong be good. Maybe this is a ux discussion.
> 
> Yea, I believe there was a little discussion about this previously in slack, but for this ticket it's just removing the alert. There should eventually be a UX ticket to add an error page or some way to allow the user to know something went wrong. For example, to test this I tried going to a a transaction that didn't exist for the report. I should probably get a 404 page, but currently it just redirects you back to the landing page with any indication something went wrong in the console.

Thanks, makes sense.  Another scenario I tried was the contact lookup (I manually edited the code to raise an error).  In this case, the lookup just spins which is why I was wondering.

**Comment by toddlees** [comment]
@dheitzer @sasha-dresden You're right.  There will be future tickets to handle errors in the UI

**Pull request merged**
