### PR TITLE
feature/943 Contact Lookup updates

### PR DESCRIPTION
**Pull request by dheitzer**
https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/943

### CODE REVIEW

**Review by toddlees — CHANGES_REQUESTED** [review]
image
looks pretty wide on F1m

**Review by toddlees — DISMISSED** [review]
image
The MAGNIFYING GLASS icon should be 20px by 20px : I'm getting a computed height of 26px
The PLUS icon it should be 20px by 20px: I'm seeing computed 22px

also pending response from @MitchellTCG about what color the dropdown background is supposed to be

**Comment by dheitzer** [comment]
> image The MAGNIFYING GLASS icon should be 20px by 20px : I'm getting a computed height of 26px The PLUS icon it should be 20px by 20px: I'm seeing computed 22px
> 
> also pending response from @MitchellTCG about what color the dropdown background is supposed to be

@toddlees clarified with @MitchellTCG yesterday that the dropdown background should always be grey.

**Comment by dheitzer** [comment]
> image The MAGNIFYING GLASS icon should be 20px by 20px : I'm getting a computed height of 26px The PLUS icon it should be 20px by 20px: I'm seeing computed 22px
> 
> also pending response from @MitchellTCG about what color the dropdown background is supposed to be

nice catch.  adjusted sizes accordingly

**Comment by dheitzer** [comment]
> image looks pretty wide on F1m

added max width to the component to now display less wide.

**Review by mjtravers — APPROVED** [review]

**Pull request merged**
