### PR TITLE
[WIP] Fix for overlapping report date issue

### PR DESCRIPTION
**Pull request by dheitzer**

### CODE REVIEW

**Comment by Elaine-Krauss-TCG** [comment]
While working on the E2E tests, I noticed an error.  You can make a report that starts before and ends after an existing report, such that the first report is entirely within the time covered by the second report.  Should be an easy fix.

image


Note: I tested this and captured this screenshot on the feature/262-unit-tests branch

**Review by toddlees — CHANGES_REQUESTED** [review]
Nice coverage!  we should probably add a test that runs the case that Elaine brings up

**Comment by dheitzer** [comment]
> While working on the E2E tests, I noticed an error. You can make a report that starts before and ends after an existing report, such that the first report is entirely within the time covered by the second report. Should be an easy fix.
> 
> image
> 
> Note: I tested this and captured this screenshot on the feature/262-unit-tests branch

Nice catch @Elaine-Krauss-TCG.  I went ahead and added a new function/tests to handle this that looks for existing coverage date start/end contained within proposed coverage dates.

**Comment by mjtravers** [comment]
OBE by [api#73](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-api/173)

**Pull request closed without merging**
